name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure and Build
        run: |
          cd backend && npm install --production
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "inventory-toolapp" #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}